baseURL = "https://example.com/"
languageCode = "en-us"
title = "Pratik"
theme = "pratik-portfolio"
copyright="Â© Pratik Patel"
googleAnalytics = ""
enableEmoji=true
enableRobotsTXT=true
pygmentsUseClasses=true
pygmentsCodeFences=true

[params.intro]
  main = "Hi, I'm Pratik :wave:"
  sub = "I'm an Analyst and Builder"



[taxonomies]
  design = "designs"
  tech = "techs"

[blackfriday]
  hrefTargetBlank = true

[params]
  breadcrumb = true
  accentColor = "#FD3519"
  mainSections = ['portfolio'] # values: ['post', 'portfolio'] only accept one section, to be displayed bellow 404
  rendererSafe = false # set to true if wish to remove the unsafe renderer setting below (recommended). Titles will not be run through markdownify

[params.notFound]
  gopher = "/images/gopher.png" # checkout https://gopherize.me/
  h1 = 'Bummer!'
  p = "It seems that this page doesn't exist."

[params.sections]
  # Define how your sections will be called
  # when automatically pulled. For instance in the 404 page
  post = "article"
  portfolio = "project"

[params.sidebar]
  backgroundImage = '' # header background image - default "/images/default_sidebar.jpg" - Photo by Tim Marshall on Unsplash
  gradientOverlay = '' # default: rgba(0,0,0,0.4),rgba(0,0,0,0.4)
  logo = "" # - default "/images/pfp.jpg"
[params.assets]
  favicon = ""
  customCSS = ""

[params.social]
  github = "https://github.com/TheNewStat1"
  twitter = "https://twitter.com/dragoontik"
  linkedin = "https://www.linkedin.com/in/paul-pratik-patel-177276a5/"
  medium = "https://medium.com/"
  codepen = "https://codepen.io/"
  facebook = "https://www.facebook.com/"

[params.contact]
  email = ""
  text= "" # text of the contact link in the sidebar. If email params.contact.email is defined


[menu]

[[menu.main]]
  identifier = "about"
  name = "About"
  title = "About section"
  url = "/"
  weight = -120

[[menu.main]]
  identifier = "portfolio"
  name = "Portfolio"
  title = "Portfolio"
  url = "/portfolio/"
  weight = -110

[[menu.main]]
  identifier = "experience"
  name = "Work Experience"
  title = "Work Experience"
  url = "/experience/"
  weight = -100

[[menu.main]]
  identifier = "papers"
  name = "White Papers"
  title = "Papers"
  url = "/papers/"
  weight = -100

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
